# Generated by Django 4.2 on 2023-04-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import submission.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('FILE', 'FILE'), ('LINK', 'LINK')], default='LINK', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_file', models.FileField(blank=True, null=True, upload_to=submission.models.username_path)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=submission.models.username_path)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
